### ISSUE TITLE
Bug: Wallet Account Changes Not Updating Properly

### ISSUE THREAD

**Issue by veratek** [bearby-wallet/bearby-web3#15]
Description:
We've noticed a problem with how the wallet handles account changes. 

Steps to Reproduce:

    Open the bridge.
    Connect Bearby wallet.
    Change your account address.
    Check if the address updates on the bridge UI.
    Change the address again.
    Notice that the address doesn't update on the UI this time.

Expected Behavior:
The account address should update on the UI every time it's changed in the wallet.

Actual Behavior:
The address updates only once after a change. Subsequent changes don't reflect on the UI.

Additional Context:
   Bug seems to be coming from : ``` web3.wallet.account.subscribe((base58) => {console.log(base58)};```

    This issue affects user experience as the UI fails to update with account changes.
    A temporary workaround is to reload the page, but it doesn't fix the problem.

**Comment by hicaru** [comment]
Thanks for your issue i will check it.

**Comment by hicaru** [comment]
thanks for your issue, it seems you are right, i will fix it in new version)))
