### ISSUE TITLE
error: recipient base58 address

### ISSUE THREAD

**Issue by lilyanB** [bearby-wallet/bearby-web3#5]
Hey, I have this error when interact with my Smart Contract:
![image](https://user-images.githubusercontent.com/91454320/232047687-5ad2046e-4961-4170-a011-7f6ecf8db55e.png)

I use this code:

```typescript

const tx = await web3.contract.call({
        maxGas: 2000000,
        coins: 0.1,
        targetAddress: "AS1DrA9jWTPKm2PgZrxqwJJvdS84VSeFbVMZFZy5NofK6tZW8WpB",
        functionName: 'closeByProvider',
        parameter: {
            swapID: swapID.toString(),
            secretKey: secretKey
        },
        fee: 0
    })

  ```
  
  swapID is a number and secretKey is a StaticArray<u8>
  
  Do you have an idea? I am available if you need more details. Thanks

**Comment by hicaru** [comment]
hello, you are right this is my address validator fail, in next release will be fixed
