### ISSUE TITLE
Implement user confirmation for each wallet account when connecting to a dApp

### ISSUE THREAD

**Issue by loonggamma** [bearby-wallet/bearby-web3#9]
**Context:**
- Currently when a user connects a Bearby wallet to a dApp he is asked to confirm the connection once. This confirmation seems to apply not to the selected but to all available user accounts, which is not an expected behavior. 
- Following the benchmark practices, browser wallets like Metamask ask the user to verify the connection request for each account, once switched. There's a period of time that Metamask allows switching between already connected wallets without additional user confirmation (try to switch between 2/3 wallets of Metamask on [Massa Bridge](https://bridge.massa.net/index)).

**Feature suggestion:**
Improve handling connection of accounts by asking user to validate connecting each wallet account to a specific dApp.

**Dependencies:**
If this feature is going to be implemented, please keep us aware in advance before going to prod, to make necessary adjustments in our code. Thanks!

**Comment by loonggamma** [comment]
@hicaru might've posted in a wrong repo, feel free to move the issue in a correct one

**Comment by hicaru** [comment]
yes, need remake this system!

**Comment by hicaru** [comment]
@longgamma-massa yes, acutally it more about beabry-extension))
